@localUrl = http://localhost:5083
@railwayUrl = https://apicentraldocsweb-production.up.railway.app

### Testar API local
GET {{localUrl}}/
Accept: application/json

### Testar API no Railway
GET {{railwayUrl}}/
Accept: application/json

### Cadastrar usuário no Railway
POST {{railwayUrl}}/api/Usuario/Cadastrar
Content-Type: application/json

{
  "nome": "Teste Railway",
  "cpf": "12345678910",
  "email": "teste.railway@email.com",
  "senha": "123",
  "confirmarSenha": "123"
}

### Login no Railway
POST {{railwayUrl}}/api/Usuario/Login
Content-Type: application/json

{
  "email": "teste.railway@email.com",
  "senha": "123"
}