// <auto-generated />
using System;
using ApiCentralDocsWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCentralDocsWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911120000_SeedTiposDocumento")]
    partial class SeedTiposDocumento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiCentralDocsWeb.Model.Documento", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("CidadeEmissao")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("DataEmissao")
                    .HasColumnType("datetime2");

                b.Property<string>("Numero")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("OrgaoEmissor")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("TipoDocumentoId")
                    .HasColumnType("int");

                b.Property<int>("UsuarioId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("TipoDocumentoId");

                b.HasIndex("UsuarioId");

                b.ToTable("Documentos");
            });

            modelBuilder.Entity("ApiCentralDocsWeb.Model.Foto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Descricao")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("DocumentoId")
                    .HasColumnType("int");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("DocumentoId");

                b.ToTable("Fotos");
            });

            modelBuilder.Entity("ApiCentralDocsWeb.Model.TipoDocumento", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("TiposDocumento");
            });

            modelBuilder.Entity("ApiCentralDocsWeb.Model.Usuario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Ativo")
                    .HasColumnType("bit");

                b.Property<string>("CPF")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("DataCriacao")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Senha")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("ApiCentralDocsWeb.Model.Documento", b =>
            {
                b.HasOne("ApiCentralDocsWeb.Model.TipoDocumento", "TipoDocumento")
                    .WithMany("Documentos")
                    .HasForeignKey("TipoDocumentoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ApiCentralDocsWeb.Model.Usuario", "Usuario")
                    .WithMany("Documentos")
                    .HasForeignKey("UsuarioId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("TipoDocumento");

                b.Navigation("Usuario");
            });

            modelBuilder.Entity("ApiCentralDocsWeb.Model.Foto", b =>
            {
                b.HasOne("ApiCentralDocsWeb.Model.Documento", "Documento")
                    .WithMany("Fotos")
                    .HasForeignKey("DocumentoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Documento");
            });

            modelBuilder.Entity("ApiCentralDocsWeb.Model.Documento", b =>
            {
                b.Navigation("Fotos");
            });

            modelBuilder.Entity("ApiCentralDocsWeb.Model.TipoDocumento", b =>
            {
                b.Navigation("Documentos");
            });

            modelBuilder.Entity("ApiCentralDocsWeb.Model.Usuario", b =>
            {
                b.Navigation("Documentos");
            });
#pragma warning restore 612, 618
        }
    }
}